export const PAYMENT_CREATE_COINBASE_CHARGE_REQUEST =
  "PAYMENT_CREATE_COINBASE_CHARGE_REQUEST";
export const PAYMENT_CREATE_COINBASE_CHARGE_SUCCESS =
  "PAYMENT_CREATE_COINBASE_CHARGE_SUCCESS";
export const PAYMENT_CREATE_COINBASE_CHARGE_FAIL =
  "PAYMENT_CREATE_COINBASE_CHARGE_FAIL";
